VERSION 0.7

ARG --global DOCKER_IMAGE_NAME=nikmmd/go_svc1:latest

deps:
    FROM golang:1.18-alpine
    WORKDIR /service/go-svc1
    COPY go.mod go.sum ./
    RUN go mod download
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

build:
    FROM +deps
    COPY main.go .
    RUN go build -o app main.go
    # SAVE ARTIFACT app AS LOCAL app # if you want to expose it to local repo too
    SAVE ARTIFACT app # this just exposes it to docker layers

unit-test:
    FROM +deps
    COPY main.go .
    COPY main_test.go .
    RUN CGO_ENABLED=0 go test

docker:
    FROM alpine:3.18.3
    USER nobody
    COPY +build/app .
    CMD ["./app"]
    SAVE IMAGE --push $DOCKER_IMAGE_NAME